name: "çª’å‹æ¢…æ ¹ 2.0ã€ŠFULLHD-2025ã€‹ é›»å½±é«˜æ¸…å®Œæ•´ç‰ˆ4K ğ“ğ– M3GAN 2.0"
author: "reniorona"
description: "Setup AWS CLI to use in github actions"
branding:
  icon: 'thumbs-up'
  color: 'white'
